Cargo.lock, Cargo.toml, bin/kona-exex/Cargo.toml, bin/kona-exex/src/cli.rs, bin/kona-exex/src/kona.rs, bin/kona-exex/src/main.rs
=> feat(kona-exex): basic exex setup & routing

Cargo.lock, Cargo.toml, crates/kona-providers/Cargo.toml, crates/kona-providers/src/chain_provider.rs, crates/ser/Cargo.toml, crates/ser/src/lib.rs, crates/ser/src/traits/compressor.rs, crates/ser/src/traits/mod.rs, crates/ser/src/types/channel_out.rs, crates/ser/src/types/mod.rs
Sets up the `ser` crate in `crates/ser`.
Ports `channel_out`.
Closes #21
=> feat(ser): Introduce ser Crate

Cargo.lock, Cargo.toml, crates/p2p/Cargo.toml, crates/p2p/src/lib.rs, crates/p2p/src/types.rs
Sets up a `p2p` crate for `hera` based off of https://github.com/paradigmxyz/reth-exex-examples/pull/15.
Makes progress on https://github.com/paradigmxyz/op-rs/issues/6
=> feat(p2p): P2P Crate

Cargo.lock, Cargo.toml, bin/op-rs/Cargo.toml, bin/op-rs/src/main.rs, crates/rollup/src/cli.rs
Adds the ability to load the rollup config from a file.
If no file is provided, the config will be loaded from the superchain registry as fallback.
=> feat(op-rs, rollup): load rollup config from file

Cargo.lock, Cargo.toml, bin/hera/Cargo.toml, crates/kona-providers/Cargo.toml, crates/kona-providers/src/blob_provider.rs, crates/kona-providers/src/lib.rs
Closes #10 
I ended up calling the provider `LayeredBlobProvider` to better encompass the fact that it supports
3 ordered methods to fetch blobs: 
1. memory
2. online CL
3. archiver
=> feat(kona-providers): layered blob provider

Cargo.lock, bin/op-rs/src/main.rs, crates/kona-providers/src/blob_provider.rs, crates/rollup/Cargo.toml, crates/rollup/src/cli.rs, crates/rollup/src/driver.rs
Added a `Driver::exex` method that can initialize a Driver with the components needed to bootstrap in ExEx mode.
Also stubbed a `StandaloneDriver` struct that will later be used to start Hera in standalone mode.
closes #8.
=> feat(rollup): init exex driver and pipeline

crates/net/src/driver.rs, crates/net/src/gossip/handler.rs, crates/net/src/types/envelope.rs
Fix #36 . This PR removed the unnecessary `Default` trait impl for `ExecutionPayloadEnvelope`. 
Replace the watch channel to std mpsc channel which no init value needed.
=> Remove `Default` trait for `ExecutionPayloadEnvelope`.

crates/net/src/builder.rs
Allows the use to specify the [`libp2p::noise::Config`](https://docs.rs/libp2p/latest/libp2p/noise/struct.Config.html) on the Network.
=> fix(net): Allow custom noise configuration

crates/net/src/builder.rs, crates/net/src/driver.rs, crates/net/src/gossip/driver.rs
> [!WARNING]
>
> Stacked ontop of #46, merge after #46.
Refactors `GossipDriver` specific logic out of the top-level `NetworkDriver` and into the `GossipDriver`.
=> feat(net): Refactor GossipDriver

Justfile, crates/net/src/builder.rs, crates/net/src/gossip/config.rs, crates/net/src/gossip/driver.rs
Allows the `NetworkDriver` builder to pass in a `libp2p::gosipsub::Config` into the builder. This replaces the idea of "extending the ConfigBuilder methods" to be more forwards-compatible.
Closes #38
=> feat(net): Pass in Gossipsub Config

Cargo.lock, bin/hera/Cargo.toml, bin/hera/src/main.rs, crates/rollup/Cargo.toml, crates/rollup/src/lib.rs, crates/rollup/src/telemetry.rs
Added the ability to start tracing to `stdout` with the following options:
- tracing target: provided by default with `RUST_LOG` directives. Falls back to `hera=info` if not provided.
- whether to show the target in stdout: `RUST_LOG_TARGET` (don't show it only when set to `0`)
- whether to use ANSI formatting and colors: `RUST_LOG_STYLE` (don't use it only if set to `never`)
Also initialized a Prometheus subscriber on the provided port.
Tested on the Hera binary.
closes #33
=> feat(rollup): init telemetry

crates/net/README.md
Small PR to mark the inline code block in the `net` crate README as `rust`.
=> fix(net): Inline Rust Code

crates/net/src/discovery/builder.rs, crates/net/src/types/enr.rs
Fixes Op Stack ENR data encoding + decoding.
Unfortunately the golang reference implementation decided to encode the opstack enr data using [unsigned varints and then using a byte string](https://github.com/ethereum-optimism/optimism/blob/develop/op-node/p2p/discovery.go#L171-L210). This PR fixes the enr data encoding + decoding in the `net` crate to perform this encoding and decoding, with tests against two enr datas generated by the reference implementation.
Closes #58
=> fix(net): Enr Data Encoding

bin/hera/src/main.rs
binds the network driver to 0.0.0.0 instead of the loopback interface.
=> fix(net): bind on unspecified socket

crates/net/README.md, crates/net/src/builder.rs, crates/net/src/discovery/builder.rs
Fix #40 
1. This PR separate gossip addr and discovery addr, if discovery addr not set, will use gossip addr instead.
2. Set the `Enr` ip and port.
=> `ListenConfig` parametrization

Cargo.lock, crates/rollup/Cargo.toml, crates/rollup/src/driver.rs
=> feat(rollup): handle chain notifications

crates/net/README.md, crates/net/src/builder.rs, crates/net/src/discovery/driver.rs
Removes localhost socket addrs to prevent loopback confusion during peer discovery.
=> fix(net): Remove localhost Sockets

Cargo.lock, Cargo.toml, crates/net/Cargo.toml, crates/net/src/types/enr.rs
Adds arbitrary property-based testing to `net` crate objects.
=> feat(net): Arbitrary Prop Testing

bin/hera/src/network.rs
=> fix(hera): Networking

crates/rollup/src/driver/cursor.rs, crates/rollup/src/driver/mod.rs, crates/rollup/src/validator.rs
This PR introduces a first iteration of the pipeline `step` functionality.
The pipeline will try to advance as long as there are new derived payloads, 
and then it will wait for a new L1 notification before trying again.
- closes #71 (first iteration, anyway)
Stack:
- #77 
- #85 
- 👉 #86
=> feat(rollup): step function

Cargo.lock, Cargo.toml, crates/kona-providers/Cargo.toml, crates/kona-providers/src/blob_provider.rs, crates/net/Cargo.toml, crates/net/src/types/envelope.rs, crates/net/src/types/payload.rs, crates/rollup/src/driver/context/mod.rs, crates/rollup/src/driver/context/standalone.rs, crates/rollup/src/driver/cursor.rs, crates/rollup/src/driver/mod.rs, crates/rollup/src/validator.rs, crates/ser/Cargo.toml, crates/ser/src/types/channel_out.rs
This PR fixes all dependency-related compile errors, mainly due to changes to location of types in different crates.
It also pins `op-alloy`, `kona` and `superchain` deps allow us to work on a stable trunk until the type migration is done.
Also removed `ssz_rs` in favor of `ethereum_ssz`, as with the new alloy version we can't access it from `private::`.
- closes #83 
Stack:
- #77 
- 👉 #85 
- #86
=> fix: compile errors due to unpinned dependencies

bin/hera/src/node.rs, crates/rollup/src/driver/cursor.rs, crates/rollup/src/driver/mod.rs, crates/rollup/src/pipeline.rs
This PR fixes the pipeline initialization by fetching the L2 chain tip and its corresponding L1 origin block info.
This also fixes the issue of not initializing the driver `SyncCursor` which would currently panic otherwise.
The `RollupPipeline` doesn't depend on an `L2ChainProvider` generic anymore, because we were using the same provider independently of the context mode. The second reason is because the `latest_block_number()` method is only available on the `AlloyL2ChainProvider` and we need to call it to fetch the L2 tip before initializing the pipeline.
If in the future we need to support different L2 providers, I suggest adding a `L2ChainProviderExt` trait which also contains the ability to fetch the latest block number, or alternatively upstream this change into `kona_derive`'s …
=> fix(rollup): init pipeline based on real l2 tip

bin/hera/src/node.rs, crates/rollup/src/driver/context/standalone.rs, crates/rollup/src/driver/cursor.rs, crates/rollup/src/driver/mod.rs, crates/rollup/src/pipeline.rs
Introduces a second method of polling via HTTP that doesn't rely on the `eth_filter` feature.
This will be auto-detected and triggered as fallback. It's mostly useful for test purposes.
- Fixes #87 
- main
- #88 
- 👉 #89
=> fix(rollup): fallback HTTP polling without filtering

bin/hera/src/node.rs, crates/rollup/src/cli.rs, crates/rollup/src/driver/context/exex.rs, crates/rollup/src/driver/context/mod.rs, crates/rollup/src/driver/context/standalone.rs, crates/rollup/src/driver/mod.rs, crates/rollup/src/lib.rs
This PR introduces a new wrapper struct: `ExExHeraContext`. 
This struct wraps `ExExContext` with a copy of `InMemoryChainProvider`, such that every newly committed chain gets automatically injected into the same L1 provider cache that's used by the rollup pipeline when running as ExEx.
This abstraction allows us to stop worrying about caching L1 blocks (which was previously marked as TODO in the derivation loop) and also makes full use of the data inside `Arc<Chain>`, such as receipts.
- main
- #88 
- #89 
- 👉 #91
=> feat(rollup): abstract L1 cache behind `ExExHeraContext`

crates/kona-providers/src/blob_provider.rs, crates/rollup/src/driver/mod.rs
This PR fixes parsing of URLs to strings by removing the trailing `/` where necessary.
=> fix: trim last / from urls

Cargo.lock, crates/kona-providers/Cargo.toml, crates/kona-providers/src/blob_provider.rs, crates/kona-providers/src/chain_provider.rs, crates/rollup/src/driver/mod.rs
Kona (one of the last few non-pinned deps) got upgraded in #96.
Finally we can get rid of `anyhow`, thanks @clabby 👑
=> fix: compile errs due to dep upgrades

Cargo.lock, Cargo.toml, bin/hera/Cargo.toml, bin/op-rs/Cargo.toml, crates/net/Cargo.toml, crates/rollup/Cargo.toml, crates/rpc/Cargo.toml, crates/rpc/src/lib.rs, crates/rpc/src/rollup.rs, crates/rpc/src/sequencer.rs, crates/ser/Cargo.toml
=> feat(rpc): Setup RPC Crate
